### ISSUE TITLE
Provide details on errors and try to recover from them

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/syblars#15]
Currently we provide a generic error message regardless of the type of the error. Instead we should provide some details. In addition, once an error occurs, the application does not seem to be able to gracefully recover from it, keeping to give errors in subsequent use.

**Comment by hasanbalci** [comment]
We now detailed explanations in the error messages. Some examples are as follows:
![error_message1](https://user-images.githubusercontent.com/22586369/189183568-2294af5f-4555-490e-bbd5-525ea731e195.png)
![error_message2](https://user-images.githubusercontent.com/22586369/189183587-7e85d298-541b-4b9d-9323-a8b51fca306b.png)
![error_message3](https://user-images.githubusercontent.com/22586369/189183600-1c34561a-597d-4c89-b413-2dc9c1504975.png)

We are also now trying to catch possible errors more tightly to prevent server to be down and show "Application Error" message. But still, if the server crashes, Heroku restarts it after a certain period of time according to its documentation.
