### ISSUE TITLE
Demo and documentation improvements 2

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/syblars#2]
Demo improvements:
- [x] 1. Change SBML sample to demonstrate more types of nodes/edges
- [x] 2. For SBML notation, we could make some node types to be lighter/darker than the chosen color for easier differentiation
- [x] 3. All the default blank font color could be changed to the dark brown in our logo
- [x] 4. About dialog should refer the user to the repository for source code and its README for further help/details on the service

README improvements:
- [x] 11. Provide a simple example of how a user can make use of the sample deployment of SyBLaRS web service, say for laying out an SBGNML map and getting the result in PNG format
- [x] 12. Under Supported Formats, document the notation used (a separate legend for each format?)

YouTube:
- [x] 21. Record a video on how one can upload a map, change both layout and image options and apply layout, download, etc.

**Comment by hasanbalci** [comment]
Now, 2, 3, 4 and 11 should be solved.

**Comment by hasanbalci** [comment]
@ugurdogrusoz Can you please check 12? I added stylesheets info under Supported Formats in README and also added them to About section of demo.

**Comment by ugurdogrusoz** [comment]
> @ugurdogrusoz Can you please check 12? I added stylesheets info under Supported Formats in README and also added them to About section of demo.

Looks great, thank you!

**Comment by hasanbalci** [comment]
I changed SBML sample. The current one shows seven types of nodes and four types of edges.
