### ISSUE TITLE
Option for not returning an image

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/syblars#4]
Currently, there is no option for not returning an image on a request. But some users might only be interested in layout and have their own rendering. Hence, we should provide an option for disabling return of an image. 
In addition, when the user doesn't specify any layout options we should assume preset layout. Similarly, when the user doesn't specify any image options, we should go with the defaults.

**Comment by hasanbalci** [comment]
I now added an option for not returning an image. Its default is true, but user is able to set it to false via url query parameter: `service_address/layout/:file_format?image=false`. In addition, now if user doesn't specify any image options, we use the default ones. 

Related to layout options, if user doesn't specify any layout options or specify preset layout, we return only image as the output. This feature can be applied in client demo by selecting preset layout from layout options.
