### ISSUE TITLE
Add support for basic graph queries

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/syblars#5]
This includes basic built-in queries in Cytoscape.js such as shortest paths.

**Comment by ugurdogrusoz** [comment]
- [x] With SBGN defaults, the color of the source node is gray when it should be green
- [x] With long node names truncated, it'd be great if the tooltips showed the entire labels
- [x] Some fields like limit and highlight width should not accept negative values (revert to the default when such values entered?)
- [x] Let's make the width of the color pickers compatible with those under Query

**Comment by hasanbalci** [comment]
For the number inputs, if user enters "-" sign it sets the value to 0, if user pastes a negative number it sets it to the absolute value of that number.
