### ISSUE TITLE
Add support for advanced graph queries

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/syblars#6]
Add support for the following advanced graph queries:
- Neighborhood
- Graph of Interest
- Common stream

**Comment by hasanbalci** [comment]
I added _neighborhood_, _common stream_, _paths between_ and _paths from to_ queries from graph-algos extension to SyBLaRS. I also tested these new queries and found iVis-at-Bilkent/cytoscape.js-graph-algos#4, iVis-at-Bilkent/cytoscape.js-graph-algos#5, iVis-at-Bilkent/cytoscape.js-graph-algos#6 issues in the extension side. While these issues are being fixed, I'll continue testing them in SyBLaRS.

**Comment by hasanbalci** [comment]
I tested queries and didn't see any problem. @ugurdogrusoz You may close it if it's ok for you as well.
