### ISSUE TITLE
Update Readme and Demo Help

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/syblars#7]
Need to update the repo Readme and the Help page in the Demo to include the new query feature.

**Comment by hasanbalci** [comment]
@ugurdogrusoz You can review Readme and Demo Help now. When the new YouTube is recorded, the video link in Demo Help will be updated.

**Comment by hasanbalci** [comment]
@ugurdogrusoz YouTube video is now ready, could you please add subtitles as before? Thanks!

**Comment by ugurdogrusoz** [comment]
https://youtu.be/dr1gqSR8OGM
