### ISSUE TITLE
Produce a series of images from a sample dataset

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/syblars#9]
To show a use case of the service, we can lay out and render the files from a sample SBGN or SBML dataset serially.

**Comment by hasanbalci** [comment]
I wrote a script for this purpose and generated images of 100 models from the BioModels dataset. The script and other related folders/files can be found in *test* branch. @ugurdogrusoz you may want to review its [README](https://github.com/iVis-at-Bilkent/syblars/tree/test).

**Comment by ugurdogrusoz** [comment]
Reviewed the README, thanks.
